import { LibraryVoice } from '../types';

/**
 * Static Voice Library catalog for SCREEN.AI / Dubnex.
 * apiVoiceKey is sent to FastAPI /process-video and resolved via VOICE_MAP for ElevenLabs.
 * previewUrl null => Preview control disabled ("Preview unavailable").
 */
export const voiceLibraryCatalog: LibraryVoice[] = [
  {
    id: 'el-george',
    name: 'George',
    provider: 'ElevenLabs',
    gender: 'Male',
    accent: 'British',
    language: 'en',
    category: 'Narration',
    supportedLanguages: ['en', 'es', 'fr', 'de', 'hi', 'pt', 'it', 'ja'],
    tags: ['narrative', 'warm', 'documentary', 'default'],
    previewUrl: null,
    apiVoiceKey: 'george',
    description: 'Warm narrative male voice suited for explainers and documentaries.',
    source: 'library',
  },
  {
    id: 'el-jessica',
    name: 'Jessica',
    provider: 'ElevenLabs',
    gender: 'Female',
    accent: 'American',
    language: 'en',
    category: 'Corporate',
    supportedLanguages: ['en', 'es', 'fr', 'de', 'pt', 'it', 'nl'],
    tags: ['clear', 'professional', 'corporate', 'bright'],
    previewUrl: null,
    apiVoiceKey: 'jessica',
    description: 'Clear professional female voice for corporate and product narration.',
    source: 'library',
  },
  {
    id: 'el-bunty',
    name: 'Bunty',
    provider: 'ElevenLabs',
    gender: 'Male',
    accent: 'Indian English',
    language: 'en',
    category: 'Conversational',
    supportedLanguages: ['en', 'hi', 'ur', 'ta', 'te', 'gu', 'pa'],
    tags: ['conversational', 'south-asian', 'friendly'],
    previewUrl: null,
    apiVoiceKey: 'bunty',
    description: 'Friendly conversational male voice with South Asian English character.',
    source: 'library',
  },
  {
    id: 'el-bella',
    name: 'Bella',
    provider: 'ElevenLabs',
    gender: 'Female',
    accent: 'American',
    language: 'en',
    category: 'Cinematic',
    supportedLanguages: ['en', 'es', 'fr', 'de', 'it', 'pt', 'pl'],
    tags: ['expressive', 'cinematic', 'emotional'],
    previewUrl: null,
    apiVoiceKey: 'bella',
    description: 'Expressive cinematic female voice for trailers and emotional scenes.',
    source: 'library',
  },
  {
    id: 'el-adam',
    name: 'Adam',
    provider: 'ElevenLabs',
    gender: 'Male',
    accent: 'American',
    language: 'en',
    category: 'Broadcast',
    supportedLanguages: ['en', 'es', 'fr', 'de', 'ja', 'ko', 'zh'],
    tags: ['deep', 'authoritative', 'news'],
    previewUrl: null,
    apiVoiceKey: 'adam',
    description: 'Deep authoritative male voice for news and technical briefs.',
    source: 'library',
  },
  {
    id: 'el-rachel',
    name: 'Rachel',
    provider: 'ElevenLabs',
    gender: 'Female',
    accent: 'American',
    language: 'en',
    category: 'Narration',
    supportedLanguages: ['en', 'es', 'fr', 'de', 'pt', 'ar'],
    tags: ['soft', 'storytelling', 'calm'],
    previewUrl: null,
    apiVoiceKey: 'rachel',
    description: 'Soft storytelling female voice for calm narration and education.',
    source: 'library',
  },
  {
    id: 'el-serena',
    name: 'Serena',
    provider: 'ElevenLabs',
    gender: 'Female',
    accent: 'British',
    language: 'en',
    category: 'Broadcast',
    supportedLanguages: ['en', 'fr', 'de', 'it', 'es'],
    tags: ['crisp', 'premium', 'broadcast'],
    previewUrl: null,
    apiVoiceKey: 'serena',
    description: 'Crisp broadcast-ready female voice with premium clarity.',
    source: 'library',
  },
  {
    id: 'el-marcus',
    name: 'Marcus',
    provider: 'ElevenLabs',
    gender: 'Neutral',
    accent: 'Neutral',
    language: 'en',
    category: 'Multilingual',
    supportedLanguages: ['en', 'es', 'fr', 'de', 'hi', 'ja', 'zh', 'ko'],
    tags: ['neutral', 'fast', 'multilingual'],
    previewUrl: null,
    apiVoiceKey: 'marcus',
    description: 'Neutral multilingual voice optimized for clear pacing across languages.',
    source: 'library',
  },
  {
    id: 'el-aria',
    name: 'Aria',
    provider: 'ElevenLabs',
    gender: 'Female',
    accent: 'Australian',
    language: 'en',
    category: 'Social',
    supportedLanguages: ['en', 'es', 'fr', 'pt'],
    tags: ['youthful', 'energetic', 'social'],
    previewUrl: null,
    apiVoiceKey: 'aria',
    description: 'Youthful energetic female voice for social and lifestyle content.',
    source: 'library',
  },
  {
    id: 'el-daniel',
    name: 'Daniel',
    provider: 'ElevenLabs',
    gender: 'Male',
    accent: 'British',
    language: 'en',
    category: 'Audiobook',
    supportedLanguages: ['en', 'fr', 'de', 'es', 'it'],
    tags: ['formal', 'audiobook', 'steady'],
    previewUrl: null,
    apiVoiceKey: 'daniel',
    description: 'Steady formal male voice suited for audiobooks and long-form dubs.',
    source: 'library',
  },
];

export const VOICE_LIBRARY_STORAGE_KEY = 'screen_ai_voice_library_prefs';

/** Resolve backend voice query key from Voice Library selection */
export function resolveApiVoiceKey(defaultVoiceId: string | null | undefined): string {
  const voice = voiceLibraryCatalog.find((v) => v.id === defaultVoiceId);
  if (voice?.apiVoiceKey) return voice.apiVoiceKey;
  if (voice?.name) return voice.name.toLowerCase();
  return 'george';
}

export function languageDisplayName(code: string): string {
  const map: Record<string, string> = {
    en: 'English',
    es: 'Spanish',
    fr: 'French',
    de: 'German',
    hi: 'Hindi',
    pt: 'Portuguese',
    it: 'Italian',
    ja: 'Japanese',
    ko: 'Korean',
    zh: 'Chinese',
    ar: 'Arabic',
    nl: 'Dutch',
    pl: 'Polish',
    ur: 'Urdu',
    ta: 'Tamil',
    te: 'Telugu',
    gu: 'Gujarati',
    pa: 'Punjabi',
  };
  return map[code] || code.toUpperCase();
}
